### ISSUE TITLE
Can I start working from today?

### ISSUE THREAD

**Issue by SaptakBhoumik** [langjam/langjam#1]
Can I start working from today because it takes a lot of time to make a programming language

**Comment by agausmann** [comment]
> it takes a lot of time to make a programming language

It can also take a lot of time to make a game, but people _can_ design and develop good games in 48 hours for game jams!  Learning how to develop at a fast pace, and learning what features _you_ can and can not complete in the given time, is definitely a big part of the challenge. Over time, you'll definitely get better at evaluating that, and your coding skills will also get better!

> Can I start working from today

You definitely can start working on tools and libraries now, as the rules say: "You can use any libraries you'd like to help build your project - lexical analysers, parser generators, codegen frameworks like llvm, you name it."

Keep in mind that the language you design for the jam should follow the theme. The theme may require some strange features / restrictions in the language, which you won't know about until the jam starts. So you'll probably have to do most or all of the  language design during the jam. So it would be wise to build a strong framework of libraries before the jam starts, so you can focus your time on design once the theme is released.

**Comment by SaptakBhoumik** [comment]
Ok
