### ISSUE TITLE
Mac/win dev and package repo‘s not up-to-date

### ISSUE THREAD

**Issue by spdegabrielle** [langjam/langjam#11]
I’d like to use Racket and other languages but 

A) I use Mac & windows
B) Debian/Ubuntu or Arch package repo‘s all have old versions of Racket

Can you clarify the rules to permit
A) allow language dev in Mac and/or Windows 
B) allow use of official installers, i.e. https://download.racket-lang.org/ for Racket, and official installers for other languages not updated in Debian/Ubuntu or Arch package repo‘s

**Comment by sophiajt** [comment]
I'm seeing 8.2 for Racket on both the website and Arch. That should be fine to use.

**Comment by sophiajt** [comment]
Going ahead and closing, I think Racket should work just fine.
