### ISSUE TITLE
Q: Will the theme be pre-released?

### ISSUE THREAD

**Issue by christhekeele** [langjam/langjam#12]
I understand a major purpose of holding the theme secret is to prevent people getting a head start on development.

Still, it would be nice—and possibly even a way to drum up some interest—if the theme or some hints about it was released a little before start; a day or two perhaps. I know it would give me some to ruminate and get hyped for the weekend ahead.

Additionally, a little extra time to think tactically about what basic stack I will use would be appreciated.

**Comment by tjjfvi** [comment]
Also, some examples of themes could be nice

**Comment by bert2** [comment]
I don't think pre-releasing the theme is a good idea for the already mentioned reason. But examples would be nice just to get an idea what to expect.

Will it be something "common" like "Halloween" and "42", or rather something compiler-related like "static type analysis" etc.?
