### ISSUE TITLE
Link not working in resources.

### ISSUE THREAD

**Issue by jecolon** [langjam/langjam#14]
In the resources file, under `Books`, the link titled `Compiler course notes for creating a Python compiler` is not working. It just hangs while trying to connect.

**Comment by sophiajt** [comment]
Good catch (and nice Rush logo :) )

I went ahead and uploaded a local copy of it.

**Comment by jecolon** [comment]
Thanks JT! Hardcore Rush fan here. Greatest band EVER!! :guitar: :drum: :guitar:
