### ISSUE TITLE
team?

### ISSUE THREAD

**Issue by halchester** [langjam/langjam#16]
Hello! so i'm new to jams and never been to coding places. I just build websites and learning new tools. I'm pretty interested in this too and I don't think I can do this alone since I'm a beginner, is there any team that I can join and help out? I know Typescript, JS, JSX and some Python.

**Comment by zoomlogo** [comment]
@halchester Hi! if you are interested; you can make an account on stack exchange (or if you already have one and have reputation > 20; you can chat [here](https://chat.stackexchange.com/rooms/128107/langjam)) and link it here. :)

**Comment by halchester** [comment]
Hey @PyGamer0, thanks for the info! but my stack exchange account is new and has 0 reputation. Is there any other place?

**Comment by tjjfvi** [comment]
@halchester You can get 20+ rep in not too long if you answer some of the challenges at https://codegolf.stackexchange.com/ :)

**Comment by zoomlogo** [comment]
@halchester I can ask the mods to give you write-access :). For that I need the link to your user account.  Or just do what @tjjfvi said. (its faster)

**Comment by halchester** [comment]
@PyGamer0 Thanks! I'll just do what @tjjfvi said!
