### ISSUE TITLE
Can I use a non-repository language with an easy install?

### ISSUE THREAD

**Issue by paulstansifer** [langjam/langjam#2]
I have a [homemade language](http://github.com/paulstansifer/unseemly)  intended for making it fast to implement new languages (in a “language-oriented programming” style, like Racket). It’s not in any repo, but it’s a Rust package, so it should fit in the three-step rule:

```
sudo apt install cargo
cargo install unseemly
unseemly $LANGUAGE_DEFINITION $PROGRAM
```

Would it be alright to use it? Unseemly is rough and unfinished enough that it might be moot, but it might be fun to take it for a spin this way.

**Comment by sophiajt** [comment]
Sorry - just saw this issue.

Yes, using a cargo package should be okay. I'll update the info section to explicitly list it.
