### ISSUE TITLE
Modification of an already existing project

### ISSUE THREAD

**Issue by massimo-zaniboni** [langjam/langjam#27]
Hi, I started one year ago (but never completed) a knowledge-base PL. I read about this JAM. I like the theme, because I can modify and maybe complete  the past project from a knowledge-base to a literate-programming PL, linking comments and code in a good way.

If I do this, do I break the rules of the JAM? Maybe I can show on a separate repo/branch the starting code and documenting the work-done for this specific JAM, that will be a lot. By the way, I doubt to finish it.

Let me know, thanks.

**Comment by sophiajt** [comment]
Generally for jams the idea is to start something new for the jam. You can use existing libraries, parser generators, etc.
