### ISSUE TITLE
Discord Invite Link is Invalid/expired

### ISSUE THREAD

**Issue by joaogui1** [langjam/langjam#29]

**Comment by sophiajt** [comment]
Is https://discord.gg/BmY6UUUU the one you tried?

Should hopefully be valid this week, I updated it yesterday

**Comment by joaogui1** [comment]
This one works, I tried the one at the bottom of readme, which is https://discord.gg/GhfDSU8Y

**Comment by greatcode** [comment]
Both are showing up as invalid or has expired
![image](https://user-images.githubusercontent.com/85716633/131399651-2596e37e-5953-4357-ac3c-7f2444671137.png)
![image](https://user-images.githubusercontent.com/85716633/131399700-2fdf7e72-3df8-45d3-981a-7400ddb568b2.png)

**Comment by tjjfvi** [comment]
Here's an invite link that will never expire: https://discord.gg/YxuJPVuyQ9

**Comment by sophiajt** [comment]
updated
