### ISSUE TITLE
Unclear language requirements

### ISSUE THREAD

**Issue by ryangjchandler** [langjam/langjam#3]
The README states that languages can be written in a language that is part of a standard Ubuntu/Debian or Arch distro. Does this mean that it has to be present on a fresh install, or just available as part of the official repositories?

**Comment by frencojobs** [comment]
I wonder too. Can I use `rust` which is to be installed with a custom script not via `apt/pacman`?

```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by sophiajt** [comment]
I've updated to make it more clear that the package just needs to be available in the package repo rather than in the default install.

rustup is optional for Rust, but yeah, that's also fine.
