### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by enderger** [langjam/langjam#30]
So, the first jam has ended and we probably should update the readme. In addition to updating the status of the aforementioned jam, I would like to see some information on when the next jam is planned and how frequently these will happen (I’d honestly say that monthly would be ideal, since the competition is rather unique compared to game jams).

**Comment by sophiajt** [comment]
Updated the readme.

Not sure of how often they'll be, but I can update the readme once we know.

**Comment by sophiajt** [comment]
Updated with info about the next lang jam
