### ISSUE TITLE
Can I use C#?

### ISSUE THREAD

**Issue by mhmd-azeez** [langjam/langjam#31]
.NET SDK is hosted in Microsoft's repo. But the installation is very simple:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-11-

```
wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0
```

Can I use it in the jam?

**Comment by cj81499** [comment]
From the readme:

> Languages you can use
>You can code in any programming language you'd like to create your project, so long as the language is part of the Debian/Ubuntu or Arch package repo (or one of the language-specific repos, like Rust's cargo). Please limit build steps of the project to three or less steps.

Personally, I'd say it's fine to use C#. It's in a language-specific repo.

**Comment by mhmd-azeez** [comment]
@cj81499 Yeah, it was not clear for me what it meant by language-specific repos. Thank you for the clarification.
