### ISSUE TITLE
Add a link that shows the time in the users time zone

### ISSUE THREAD

**Issue by esoterra** [langjam/langjam#6]
Add a link that makes it easy for users to tell when the event occurs in their timezone.
Here's one I put together based on the info in the readme. Feel free to use it if it's correct.

https://dateful.com/eventlink/1037709179

There are also other services like [this](https://www.timeanddate.com/worldclock/fixedform.html) and probably more I didn't find.

**Comment by sophiajt** [comment]
Closed with #9
